version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing root dependencies..."
  build:
    commands:
      - echo "Building the backend application..."
      - echo "Installing backend dependencies..."
      
